### ISSUE TITLE
'skip' does nothing

### ISSUE THREAD

**Issue by rlyons** [Plaristote/sharepoint-ruby#21]
list.find_items skip: 50 
this doesn't acutally seem to do anything.  I can't paginate...  is there a way for us to find the valid tokens to use for our sharepoint installation?

**Comment by Plaristote** [comment]
Well, that gem isn't up to date with the latest version of Sharepoint.
I have no idea if the API has changed. I've looked, by I just cannot find out any documentation on the new Sharepoint version. It's unlikely, but they may have changed the way this works.

Anyhow, I do not have any Sharepoint server with which I can try to figure out these kind of issues. I can only tell that this used to work with Sharepoint Online 2013, but since I've stopped working on Sharepoint sites, I can't really keep up with all the new stuff...

If I were you, I'd either:
- Read the queries made by sharepoint-ruby using something like Wireshark ;
- Add some debug logs at the beginning/end of requests of sharepoint-ruby (editing the sharepoint-ruby.rb file, in the `query` method) to find out what's being sent and what's the server's answer.

I'd then read the result and compare them with the documentation for Sharepoint's REST API.

In that regard, the gem uses curl to make its request, and I'm pretty sure we had an option to enable the verbose mode, which gave plenty of data about all the queries that were made. You can enable it this way:
```
site = Sharepoint::Site.new 'mysite.sharepoint.com', 'server-relative-site-url'
site.verbose = true
```

The skip option is supposed to be part of the url. So you should check that the query's url does includes a `skip` parameter with the proper value.

**Comment by stootles** [comment]
So there has been an API changed and this blog sums it up: http://www.dev4side.com/en/blog/posts/2014/04/10/list-elements-pagination-with-sharepoint-2013-rest-api-%E2%80%93-part-1

In short, there is a URL placed in the response to give the URL for the next part of the list results.

**Comment by Plaristote** [comment]
Interesting. If I got it right, it means that if we want to fetch the tenth page, we have to download the 10 first pages in order. It'll take a moment to implement this behavior properly, but I'll look into it soon.

Thanks for the help !
